test_0 (__main__.lab2a.test_0)
[Lab 2] - [Investigation 1] - [Part 1] - variables & printing - Test for file creation: ./lab2a.py ... ok
test_1 (__main__.lab2a.test_1)
[Lab 2] - [Investigation 1] - [Part 1] - variables & printing - Test for errors running: ./lab2a.py ... /usr/lib/python3.12/subprocess.py:822: ResourceWarning: unclosed file <_io.TextIOWrapper name=3 encoding='UTF-8'>
  _cleanup()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
ok
test_2 (__main__.lab2a.test_2)
[Lab 2] - [Investigation 1] - [Part 1] - variables & printing - Test for correct shebang line: ./lab2a.py ... ok
test_3 (__main__.lab2a.test_3)
[Lab 2] - [Investigation 1] - [Part 1] - variables & printing - Test for correct output: ./lab2a.py ... FAIL

======================================================================
FAIL: test_3 (__main__.lab2a.test_3)
[Lab 2] - [Investigation 1] - [Part 1] - variables & printing - Test for correct output: ./lab2a.py
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lwaterman1/ops445/lab2/./CheckLab2.py", line 73, in test_3
    self.assertEqual(stdout, expected_output, msg=error_output)
AssertionError: b'' != b'Hi Jon, you are 20 years old.\n' : output is not correct (HINT: pay attention to uppercase letters, spaces, and punctuation)

----------------------------------------------------------------------
Ran 4 tests in 0.040s

FAILED (failures=1)
OPS445 Lab Report - System Information for running ./CheckLab2.py
=================================================================
    User login name: lwaterman1
    Git Email: lwaterman1@myseneca.ca
    Linux system name: lwaterman1-virtual-machine
    Python executable: /usr/bin/python3
    Python version:  3.12.3 (main, Apr 10 2024, 05:33:47) [GCC 13.2.0]
    OS Platform: linux
    Working Directory: /home/lwaterman1/ops445/lab2
    Start at: Fri Jan 24 12:18:50 2025
=================================================================
